### ISSUE TITLE
Extract an logmatic-java project ?

### ISSUE THREAD

**Issue by drazzib** [logmatic/logmatic-android#2]
Hi there !

Do you have any plans to extract a logmatic-java project ?
IMHO, it would be greate to provide some low level primitive like :
- Connect to endpoint over TCP/UDP/HTTP
- Provide batching of messages
- Formating of stacktraces
  (like logmatic-js)

Regards,

**Comment by gpolaert** [comment]
Hi @drazzib,
Sorry I miss your message.

What do you mean by extracting a logmatic-java? Could you give me more hints about the goal?
